name: deanozar
favicon: null
layout_spectrum: 0.08663886645808816
typography_spectrum: 0.06410300359129906
title: About me
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.36316315876320004
  lightness: 0.025566663360223174
  saturation: 0.13122488162480295
  rhythmicContrast: 0.6134474754799157
purpose: []
